version: "3"

services:
    vision_service_cpu:
      build: .
      command: /bin/sh -c "pip install -r requirements.txt && python3 broker.py"
      environment:
        - MQTT_URL=${MQTT_URL}
      volumes:
        - .:/usr/src/app